kind: pipeline
type: docker
name: hawk

platform:
  os: linux
  arch: amd64

steps:
  - name: rocky9
    image: docker.io/hyunghwan/dev:gcc.rocky9
    commands:
      - find . -exec touch -r {} +
      - mkdir -p bld/rocky9 && cd bld/rocky9
      - ../../configure && make && { make check || { cat t/test-suite.log; /bin/false; } }

  - name: rocky9-release-rpms
    image: docker.io/plugins/gitea-release:latest
    settings:
      files:
        - "bld/rocky9/pkgs/RPM/RPMS/*/*.rpm"
        - "bld/rocky9/pkgs/RPM/SRPMS/*.src.rpm"
      base_url: https://code.miflux.com
      api_key:
         from_secret: gitea-api-key-to-code-miflux-com
    when:
      event:
        - tag
